site_name: quick_trade
nav:
    - Home: index.md
    - documentation:
          - all doc: all.md
          - trading_sys: trading_sys.md
          - utils: utils.md
    - install: install.md
    - About: about.md
theme: readthedocs